/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TickSizeIdxRouteImport } from './routes/tick-size-idx'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RumusFeeBrokerIdxRouteImport } from './routes/rumus-fee-broker-idx'
import { Route as PanduanAveragingDownRouteImport } from './routes/panduan-averaging-down'
import { Route as IndexRouteImport } from './routes/index'

const TickSizeIdxRoute = TickSizeIdxRouteImport.update({
  id: '/tick-size-idx',
  path: '/tick-size-idx',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RumusFeeBrokerIdxRoute = RumusFeeBrokerIdxRouteImport.update({
  id: '/rumus-fee-broker-idx',
  path: '/rumus-fee-broker-idx',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanAveragingDownRoute = PanduanAveragingDownRouteImport.update({
  id: '/panduan-averaging-down',
  path: '/panduan-averaging-down',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panduan-averaging-down': typeof PanduanAveragingDownRoute
  '/rumus-fee-broker-idx': typeof RumusFeeBrokerIdxRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tick-size-idx': typeof TickSizeIdxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panduan-averaging-down': typeof PanduanAveragingDownRoute
  '/rumus-fee-broker-idx': typeof RumusFeeBrokerIdxRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tick-size-idx': typeof TickSizeIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panduan-averaging-down': typeof PanduanAveragingDownRoute
  '/rumus-fee-broker-idx': typeof RumusFeeBrokerIdxRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tick-size-idx': typeof TickSizeIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panduan-averaging-down'
    | '/rumus-fee-broker-idx'
    | '/sitemap.xml'
    | '/tick-size-idx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/panduan-averaging-down'
    | '/rumus-fee-broker-idx'
    | '/sitemap.xml'
    | '/tick-size-idx'
  id:
    | '__root__'
    | '/'
    | '/panduan-averaging-down'
    | '/rumus-fee-broker-idx'
    | '/sitemap.xml'
    | '/tick-size-idx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanduanAveragingDownRoute: typeof PanduanAveragingDownRoute
  RumusFeeBrokerIdxRoute: typeof RumusFeeBrokerIdxRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TickSizeIdxRoute: typeof TickSizeIdxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tick-size-idx': {
      id: '/tick-size-idx'
      path: '/tick-size-idx'
      fullPath: '/tick-size-idx'
      preLoaderRoute: typeof TickSizeIdxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rumus-fee-broker-idx': {
      id: '/rumus-fee-broker-idx'
      path: '/rumus-fee-broker-idx'
      fullPath: '/rumus-fee-broker-idx'
      preLoaderRoute: typeof RumusFeeBrokerIdxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan-averaging-down': {
      id: '/panduan-averaging-down'
      path: '/panduan-averaging-down'
      fullPath: '/panduan-averaging-down'
      preLoaderRoute: typeof PanduanAveragingDownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanduanAveragingDownRoute: PanduanAveragingDownRoute,
  RumusFeeBrokerIdxRoute: RumusFeeBrokerIdxRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TickSizeIdxRoute: TickSizeIdxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
